baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dexter Leng'
theme = 'plain'

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false