baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
